---
## Playbook to configure Nexus Switches

- hosts: nxos

  tasks:
    - name: Configure single command on Nexus
      nxos_config:
        lines: ntp server 9.9.9.9 use-vrf default
        save_when: modified